/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedeIndexRouteImport } from './routes/rede.index'
import { Route as UnidadeUnidadeIdRouteImport } from './routes/unidade.$unidadeId'
import { Route as RedeConfiguracoesRouteImport } from './routes/rede.configuracoes'
import { Route as RedeAlertasRouteImport } from './routes/rede.alertas'
import { Route as UnidadeUnidadeIdIndexRouteImport } from './routes/unidade.$unidadeId.index'
import { Route as UnidadeUnidadeIdPedidosRouteImport } from './routes/unidade.$unidadeId.pedidos'
import { Route as UnidadeUnidadeIdConfiguracoesRouteImport } from './routes/unidade.$unidadeId.configuracoes'
import { Route as UnidadeUnidadeIdCardapioRouteImport } from './routes/unidade.$unidadeId.cardapio'
import { Route as UnidadeUnidadeIdAvaliacoesRouteImport } from './routes/unidade.$unidadeId.avaliacoes'

const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeIndexRoute = RedeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RedeRoute,
} as any)
const UnidadeUnidadeIdRoute = UnidadeUnidadeIdRouteImport.update({
  id: '/unidade/$unidadeId',
  path: '/unidade/$unidadeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeConfiguracoesRoute = RedeConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => RedeRoute,
} as any)
const RedeAlertasRoute = RedeAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => RedeRoute,
} as any)
const UnidadeUnidadeIdIndexRoute = UnidadeUnidadeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnidadeUnidadeIdRoute,
} as any)
const UnidadeUnidadeIdPedidosRoute = UnidadeUnidadeIdPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => UnidadeUnidadeIdRoute,
} as any)
const UnidadeUnidadeIdConfiguracoesRoute =
  UnidadeUnidadeIdConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => UnidadeUnidadeIdRoute,
  } as any)
const UnidadeUnidadeIdCardapioRoute =
  UnidadeUnidadeIdCardapioRouteImport.update({
    id: '/cardapio',
    path: '/cardapio',
    getParentRoute: () => UnidadeUnidadeIdRoute,
  } as any)
const UnidadeUnidadeIdAvaliacoesRoute =
  UnidadeUnidadeIdAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => UnidadeUnidadeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rede': typeof RedeRouteWithChildren
  '/rede/alertas': typeof RedeAlertasRoute
  '/rede/configuracoes': typeof RedeConfiguracoesRoute
  '/unidade/$unidadeId': typeof UnidadeUnidadeIdRouteWithChildren
  '/rede/': typeof RedeIndexRoute
  '/unidade/$unidadeId/avaliacoes': typeof UnidadeUnidadeIdAvaliacoesRoute
  '/unidade/$unidadeId/cardapio': typeof UnidadeUnidadeIdCardapioRoute
  '/unidade/$unidadeId/configuracoes': typeof UnidadeUnidadeIdConfiguracoesRoute
  '/unidade/$unidadeId/pedidos': typeof UnidadeUnidadeIdPedidosRoute
  '/unidade/$unidadeId/': typeof UnidadeUnidadeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rede/alertas': typeof RedeAlertasRoute
  '/rede/configuracoes': typeof RedeConfiguracoesRoute
  '/rede': typeof RedeIndexRoute
  '/unidade/$unidadeId/avaliacoes': typeof UnidadeUnidadeIdAvaliacoesRoute
  '/unidade/$unidadeId/cardapio': typeof UnidadeUnidadeIdCardapioRoute
  '/unidade/$unidadeId/configuracoes': typeof UnidadeUnidadeIdConfiguracoesRoute
  '/unidade/$unidadeId/pedidos': typeof UnidadeUnidadeIdPedidosRoute
  '/unidade/$unidadeId': typeof UnidadeUnidadeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rede': typeof RedeRouteWithChildren
  '/rede/alertas': typeof RedeAlertasRoute
  '/rede/configuracoes': typeof RedeConfiguracoesRoute
  '/unidade/$unidadeId': typeof UnidadeUnidadeIdRouteWithChildren
  '/rede/': typeof RedeIndexRoute
  '/unidade/$unidadeId/avaliacoes': typeof UnidadeUnidadeIdAvaliacoesRoute
  '/unidade/$unidadeId/cardapio': typeof UnidadeUnidadeIdCardapioRoute
  '/unidade/$unidadeId/configuracoes': typeof UnidadeUnidadeIdConfiguracoesRoute
  '/unidade/$unidadeId/pedidos': typeof UnidadeUnidadeIdPedidosRoute
  '/unidade/$unidadeId/': typeof UnidadeUnidadeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rede'
    | '/rede/alertas'
    | '/rede/configuracoes'
    | '/unidade/$unidadeId'
    | '/rede/'
    | '/unidade/$unidadeId/avaliacoes'
    | '/unidade/$unidadeId/cardapio'
    | '/unidade/$unidadeId/configuracoes'
    | '/unidade/$unidadeId/pedidos'
    | '/unidade/$unidadeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rede/alertas'
    | '/rede/configuracoes'
    | '/rede'
    | '/unidade/$unidadeId/avaliacoes'
    | '/unidade/$unidadeId/cardapio'
    | '/unidade/$unidadeId/configuracoes'
    | '/unidade/$unidadeId/pedidos'
    | '/unidade/$unidadeId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/rede'
    | '/rede/alertas'
    | '/rede/configuracoes'
    | '/unidade/$unidadeId'
    | '/rede/'
    | '/unidade/$unidadeId/avaliacoes'
    | '/unidade/$unidadeId/cardapio'
    | '/unidade/$unidadeId/configuracoes'
    | '/unidade/$unidadeId/pedidos'
    | '/unidade/$unidadeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RedeRoute: typeof RedeRouteWithChildren
  UnidadeUnidadeIdRoute: typeof UnidadeUnidadeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede/': {
      id: '/rede/'
      path: '/'
      fullPath: '/rede/'
      preLoaderRoute: typeof RedeIndexRouteImport
      parentRoute: typeof RedeRoute
    }
    '/unidade/$unidadeId': {
      id: '/unidade/$unidadeId'
      path: '/unidade/$unidadeId'
      fullPath: '/unidade/$unidadeId'
      preLoaderRoute: typeof UnidadeUnidadeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede/configuracoes': {
      id: '/rede/configuracoes'
      path: '/configuracoes'
      fullPath: '/rede/configuracoes'
      preLoaderRoute: typeof RedeConfiguracoesRouteImport
      parentRoute: typeof RedeRoute
    }
    '/rede/alertas': {
      id: '/rede/alertas'
      path: '/alertas'
      fullPath: '/rede/alertas'
      preLoaderRoute: typeof RedeAlertasRouteImport
      parentRoute: typeof RedeRoute
    }
    '/unidade/$unidadeId/': {
      id: '/unidade/$unidadeId/'
      path: '/'
      fullPath: '/unidade/$unidadeId/'
      preLoaderRoute: typeof UnidadeUnidadeIdIndexRouteImport
      parentRoute: typeof UnidadeUnidadeIdRoute
    }
    '/unidade/$unidadeId/pedidos': {
      id: '/unidade/$unidadeId/pedidos'
      path: '/pedidos'
      fullPath: '/unidade/$unidadeId/pedidos'
      preLoaderRoute: typeof UnidadeUnidadeIdPedidosRouteImport
      parentRoute: typeof UnidadeUnidadeIdRoute
    }
    '/unidade/$unidadeId/configuracoes': {
      id: '/unidade/$unidadeId/configuracoes'
      path: '/configuracoes'
      fullPath: '/unidade/$unidadeId/configuracoes'
      preLoaderRoute: typeof UnidadeUnidadeIdConfiguracoesRouteImport
      parentRoute: typeof UnidadeUnidadeIdRoute
    }
    '/unidade/$unidadeId/cardapio': {
      id: '/unidade/$unidadeId/cardapio'
      path: '/cardapio'
      fullPath: '/unidade/$unidadeId/cardapio'
      preLoaderRoute: typeof UnidadeUnidadeIdCardapioRouteImport
      parentRoute: typeof UnidadeUnidadeIdRoute
    }
    '/unidade/$unidadeId/avaliacoes': {
      id: '/unidade/$unidadeId/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/unidade/$unidadeId/avaliacoes'
      preLoaderRoute: typeof UnidadeUnidadeIdAvaliacoesRouteImport
      parentRoute: typeof UnidadeUnidadeIdRoute
    }
  }
}

interface RedeRouteChildren {
  RedeAlertasRoute: typeof RedeAlertasRoute
  RedeConfiguracoesRoute: typeof RedeConfiguracoesRoute
  RedeIndexRoute: typeof RedeIndexRoute
}

const RedeRouteChildren: RedeRouteChildren = {
  RedeAlertasRoute: RedeAlertasRoute,
  RedeConfiguracoesRoute: RedeConfiguracoesRoute,
  RedeIndexRoute: RedeIndexRoute,
}

const RedeRouteWithChildren = RedeRoute._addFileChildren(RedeRouteChildren)

interface UnidadeUnidadeIdRouteChildren {
  UnidadeUnidadeIdAvaliacoesRoute: typeof UnidadeUnidadeIdAvaliacoesRoute
  UnidadeUnidadeIdCardapioRoute: typeof UnidadeUnidadeIdCardapioRoute
  UnidadeUnidadeIdConfiguracoesRoute: typeof UnidadeUnidadeIdConfiguracoesRoute
  UnidadeUnidadeIdPedidosRoute: typeof UnidadeUnidadeIdPedidosRoute
  UnidadeUnidadeIdIndexRoute: typeof UnidadeUnidadeIdIndexRoute
}

const UnidadeUnidadeIdRouteChildren: UnidadeUnidadeIdRouteChildren = {
  UnidadeUnidadeIdAvaliacoesRoute: UnidadeUnidadeIdAvaliacoesRoute,
  UnidadeUnidadeIdCardapioRoute: UnidadeUnidadeIdCardapioRoute,
  UnidadeUnidadeIdConfiguracoesRoute: UnidadeUnidadeIdConfiguracoesRoute,
  UnidadeUnidadeIdPedidosRoute: UnidadeUnidadeIdPedidosRoute,
  UnidadeUnidadeIdIndexRoute: UnidadeUnidadeIdIndexRoute,
}

const UnidadeUnidadeIdRouteWithChildren =
  UnidadeUnidadeIdRoute._addFileChildren(UnidadeUnidadeIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RedeRoute: RedeRouteWithChildren,
  UnidadeUnidadeIdRoute: UnidadeUnidadeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
