/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUnitUnitIdRouteImport } from './routes/dashboard.unit.$unitId'
import { Route as DashboardUnitUnitIdIndexRouteImport } from './routes/dashboard.unit.$unitId.index'
import { Route as DashboardUnitUnitIdPedidosRouteImport } from './routes/dashboard.unit.$unitId.pedidos'
import { Route as DashboardUnitUnitIdConfiguracoesRouteImport } from './routes/dashboard.unit.$unitId.configuracoes'
import { Route as DashboardUnitUnitIdCardapioRouteImport } from './routes/dashboard.unit.$unitId.cardapio'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnitUnitIdRoute = DashboardUnitUnitIdRouteImport.update({
  id: '/unit/$unitId',
  path: '/unit/$unitId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnitUnitIdIndexRoute =
  DashboardUnitUnitIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardUnitUnitIdRoute,
  } as any)
const DashboardUnitUnitIdPedidosRoute =
  DashboardUnitUnitIdPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => DashboardUnitUnitIdRoute,
  } as any)
const DashboardUnitUnitIdConfiguracoesRoute =
  DashboardUnitUnitIdConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => DashboardUnitUnitIdRoute,
  } as any)
const DashboardUnitUnitIdCardapioRoute =
  DashboardUnitUnitIdCardapioRouteImport.update({
    id: '/cardapio',
    path: '/cardapio',
    getParentRoute: () => DashboardUnitUnitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/unit/$unitId': typeof DashboardUnitUnitIdRouteWithChildren
  '/dashboard/unit/$unitId/cardapio': typeof DashboardUnitUnitIdCardapioRoute
  '/dashboard/unit/$unitId/configuracoes': typeof DashboardUnitUnitIdConfiguracoesRoute
  '/dashboard/unit/$unitId/pedidos': typeof DashboardUnitUnitIdPedidosRoute
  '/dashboard/unit/$unitId/': typeof DashboardUnitUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/unit/$unitId/cardapio': typeof DashboardUnitUnitIdCardapioRoute
  '/dashboard/unit/$unitId/configuracoes': typeof DashboardUnitUnitIdConfiguracoesRoute
  '/dashboard/unit/$unitId/pedidos': typeof DashboardUnitUnitIdPedidosRoute
  '/dashboard/unit/$unitId': typeof DashboardUnitUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/unit/$unitId': typeof DashboardUnitUnitIdRouteWithChildren
  '/dashboard/unit/$unitId/cardapio': typeof DashboardUnitUnitIdCardapioRoute
  '/dashboard/unit/$unitId/configuracoes': typeof DashboardUnitUnitIdConfiguracoesRoute
  '/dashboard/unit/$unitId/pedidos': typeof DashboardUnitUnitIdPedidosRoute
  '/dashboard/unit/$unitId/': typeof DashboardUnitUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/unit/$unitId'
    | '/dashboard/unit/$unitId/cardapio'
    | '/dashboard/unit/$unitId/configuracoes'
    | '/dashboard/unit/$unitId/pedidos'
    | '/dashboard/unit/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/unit/$unitId/cardapio'
    | '/dashboard/unit/$unitId/configuracoes'
    | '/dashboard/unit/$unitId/pedidos'
    | '/dashboard/unit/$unitId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/unit/$unitId'
    | '/dashboard/unit/$unitId/cardapio'
    | '/dashboard/unit/$unitId/configuracoes'
    | '/dashboard/unit/$unitId/pedidos'
    | '/dashboard/unit/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/unit/$unitId': {
      id: '/dashboard/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/dashboard/unit/$unitId'
      preLoaderRoute: typeof DashboardUnitUnitIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/unit/$unitId/': {
      id: '/dashboard/unit/$unitId/'
      path: '/'
      fullPath: '/dashboard/unit/$unitId/'
      preLoaderRoute: typeof DashboardUnitUnitIdIndexRouteImport
      parentRoute: typeof DashboardUnitUnitIdRoute
    }
    '/dashboard/unit/$unitId/pedidos': {
      id: '/dashboard/unit/$unitId/pedidos'
      path: '/pedidos'
      fullPath: '/dashboard/unit/$unitId/pedidos'
      preLoaderRoute: typeof DashboardUnitUnitIdPedidosRouteImport
      parentRoute: typeof DashboardUnitUnitIdRoute
    }
    '/dashboard/unit/$unitId/configuracoes': {
      id: '/dashboard/unit/$unitId/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/unit/$unitId/configuracoes'
      preLoaderRoute: typeof DashboardUnitUnitIdConfiguracoesRouteImport
      parentRoute: typeof DashboardUnitUnitIdRoute
    }
    '/dashboard/unit/$unitId/cardapio': {
      id: '/dashboard/unit/$unitId/cardapio'
      path: '/cardapio'
      fullPath: '/dashboard/unit/$unitId/cardapio'
      preLoaderRoute: typeof DashboardUnitUnitIdCardapioRouteImport
      parentRoute: typeof DashboardUnitUnitIdRoute
    }
  }
}

interface DashboardUnitUnitIdRouteChildren {
  DashboardUnitUnitIdCardapioRoute: typeof DashboardUnitUnitIdCardapioRoute
  DashboardUnitUnitIdConfiguracoesRoute: typeof DashboardUnitUnitIdConfiguracoesRoute
  DashboardUnitUnitIdPedidosRoute: typeof DashboardUnitUnitIdPedidosRoute
  DashboardUnitUnitIdIndexRoute: typeof DashboardUnitUnitIdIndexRoute
}

const DashboardUnitUnitIdRouteChildren: DashboardUnitUnitIdRouteChildren = {
  DashboardUnitUnitIdCardapioRoute: DashboardUnitUnitIdCardapioRoute,
  DashboardUnitUnitIdConfiguracoesRoute: DashboardUnitUnitIdConfiguracoesRoute,
  DashboardUnitUnitIdPedidosRoute: DashboardUnitUnitIdPedidosRoute,
  DashboardUnitUnitIdIndexRoute: DashboardUnitUnitIdIndexRoute,
}

const DashboardUnitUnitIdRouteWithChildren =
  DashboardUnitUnitIdRoute._addFileChildren(DashboardUnitUnitIdRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUnitUnitIdRoute: typeof DashboardUnitUnitIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUnitUnitIdRoute: DashboardUnitUnitIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
